version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    command: >
      sh -c "sleep 5 && flask db upgrade &&
             flask run --host=0.0.0.0 --port=8000"

    env_file:
      - .env
    restart: on-failure
    depends_on:
      - db


  db:
    image: mysql:latest
    volumes:
      - db_mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "product"
      MYSQL_USER: "superuser"
      MYSQL_PASSWORD: "password"


  redis:
    hostname: redis
    image: "redis:alpine"
    volumes:
      - redis_data:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "flask db upgrade &&
            celery -A celery_ worker -l INFO -P solo "
    depends_on:
      - db
      - redis
    restart: on-failure
    env_file:
      - .env

volumes:
  db_mysql_data:
  redis_data:
